name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Backend
        run: |
          python app.py > logs.txt 2>&1

      - name: Send Logs to Analyzer
        if: failure()
        run: |
          curl -X POST  https://entryway-calculate-visibly.ngrok-free.dev/analyze \
          -H "Content-Type: text/plain" \
          --data-binary @logs.txt