name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest > logs.txt 2>&1

      - name: Notify AI Diagnosis Backend
        if: failure()
        run: |
          curl -X POST https://4532-45-112-138-10.ngrok-free.app/api/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "source": "github",
              "repo": "${{ github.repository }}",
              "run_id": "${{ github.run_id }}",
              "ref": "${{ github.ref_name }}"
            }'